#------------------------基础配置------------------------#
mixed-port: 7890            # 混合端口：HTTP(S)和SOCKS5共用端口
geodata-mode: true          # GEO模式：true使用geoip.dat数据库,false使用mmdb数据库
tcp-concurrent: true        # TCP并发：允许并发连接TCP,提高并发性能
unified-delay: true         # 统一延迟：统一显示节点延迟
allow-lan: true            # 局域网连接：允许其他设备经过本机代理
bind-address: "*"          # 监听地址：*表示绑定所有IP地址
find-process-mode: strict  # 进程匹配模式：strict严格,off关闭,always总是
ipv6: false               # IPv6开关：是否启用IPv6支持

# 运行模式(任选其一):
# rule: 规则模式 - 根据规则匹配来选择代理
# global: 全局模式 - 全部流量走代理
# direct: 直连模式 - 全部流量不走代理
mode: global

# 日志等级(按详细程度排序):
# debug: 调试
# info: 信息
# warning: 警告
# error: 错误
# silent: 静默
log-level: info

# 外部控制设置
external-controller: 0.0.0.0:9090  # 外部控制器监听地址
external-ui: folder               # 外部控制器UI目录
secret: ""                        # 外部控制器密码

#------------------------性能调优------------------------#
tcp-concurrent-users: 64      # TCP并发连接数,根据服务器性能调整,建议值:16-128
keep-alive-interval: 15       # 保活心跳间隔(秒),建议值:15-30
inbound-tfo: true            # 入站TCP Fast Open
outbound-tfo: true           # 出站TCP Fast Open
# Windows示例
#interface-name: WLAN   # Windows中的无线网卡名称
# 或
#interface-name: 以太网  # Windows中的有线网卡名称
# macOS示例
#interface-name: en0    # macOS中通常是Wi-Fi
# 或
#interface-name: en1    # macOS中通常是有线网卡
# Linux示例
#interface-name: eth0   # Linux中常见的有线网卡名
# 或
#interface-name: wlan0  # Linux中常见的无线网卡名

# 连接池配置
connection-pool-size: 256     # 连接池大小,建议值:128-512
idle-timeout: 60             # 空闲超时时间(秒)

#------------------------TLS 配置------------------------#
tls:
  enable: true               # 启用TLS支持
  skip-cert-verify: false    # 是否跳过证书验证
  alpn:                      # 应用层协议协商
    - h2                     # HTTP/2
    - http/1.1              # HTTP/1.1
  min-version: "1.2"        # 最低TLS版本
  max-version: "1.3"        # 最高TLS版本
  cipher-suites:            # 加密套件优先级
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305

#------------------------DNS 配置------------------------#
dns:
  enable: true              # 启用DNS服务器
  prefer-h3: true          # 优先使用HTTP/3查询
  ipv6: false              # DNS解析IPv6
  listen: 0.0.0.0:53       # DNS监听地址
  enhanced-mode: fake-ip   # DNS模式: fake-ip或redir-host
  use-hosts: true          # 使用hosts文件

  # 默认DNS服务器(用于解析其他DNS服务器的域名)
  default-nameserver:
    - 223.5.5.5            # 阿里DNS
    - 119.29.29.29         # 腾讯DNS

  # DNS服务器分流策略
  nameserver-policy:
    'www.google.com': 'https://dns.google/dns-query'      # Google域名使用Google DNS
    'www.facebook.com': 'https://dns.google/dns-query'    # Facebook域名使用Google DNS
    '.cn': 'https://doh.pub/dns-query'                    # 中国域名使用国内DNS

  # Fake-IP配置
  fake-ip-range: 198.18.0.1/16    # Fake-IP地址段
  fake-ip-filter:                 # Fake-IP过滤清单
    - "*.lan"                     # 本地域名
    - "localhost.ptlogin2.qq.com" # QQ登录

  # 主要DNS服务器
  nameserver:
    # 国内DNS服务器
    - https://doh.pub/dns-query#h3=true                # DNSPod DOH
    - https://dns.alidns.com/dns-query#h3=true         # 阿里 DOH
    - tls://223.5.5.5:853                              # 阿里 DOT

    # 国外DNS服务器
    - https://dns.google/dns-query#h3=true             # Google DOH
    - https://cloudflare-dns.com/dns-query#h3=true     # Cloudflare DOH
    - quic://dns.adguard.com:784                       # AdGuard DOQ

  # 备用DNS服务器(用于解析国外域名)
  fallback:
    - https://dns.google/dns-query#h3=true
    - https://1.1.1.1/dns-query#h3=true
    - tls://8.8.8.8:853